### ISSUE TITLE
导入clash verge规则，所有的clash都瘫痪了，求救

### ISSUE THREAD

**Issue by zhl111** [DustinWin/clash-ruleset#2]
我按照你的说明里的第三步导入clash verge规则，结果所有的机场都不能用了，怎么恢复以前的可以用的状态？
![image](https://github.com/DustinWin/clash-ruleset/assets/29135984/5e99408e-3dbf-4c5a-80c7-5aa1ae9c98b6)

是不是要恢复这两条被杀掉的进程？如何搞？
taskkill /f /t /im "Clash Verge*"`
`taskkill /f /t /im clash-meta*

**Comment by DustinWin** [comment]
> 我按照你的说明里的第三步导入clash verge规则，结果所有的机场都不能用了，怎么恢复以前的可以用的状态？ ![image](https://private-user-images.githubusercontent.com/29135984/289367399-5e99408e-3dbf-4c5a-80c7-5aa1ae9c98b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzYwNjksIm5iZiI6MTcwMjIzNTc2OSwicGF0aCI6Ii8yOTEzNTk4NC8yODkzNjczOTktNWU5OTQwOGUtM2RiZi00YzVhLTgwYzctNWFhMWFlOWM5OGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE5MTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OTZiZmNhYzMyZWQyODBhOWMwMDYxNThhM2U3NDJmNDNjZjBjYjEzMmMzZTRjYjc2N2EzOTQxMGZmY2M5ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QyIrYF3FdWk_q7q666wfUjSKC_j8u4JkFN_MW7PriaU)
> 
> 是不是要恢复这两条被杀掉的进程？如何搞？ taskkill /f /t /im "Clash Verge*"` `taskkill /f /t /im clash-meta*

`cdn.jsdelivr.net` 被污染了，改成 `fastly.jsdelivr.net` 试试。

**Comment by DustinWin** [comment]
> OK，还一个问题：我生成的merge文件，需要拷贝什么内容吗？我现在就是默认的文件，需要填入什么内容吗？ ![image](https://private-user-images.githubusercontent.com/29135984/289409279-1e2bb0ac-4251-4e25-b75f-1c5c339ba3c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjIwNTQsIm5iZiI6MTcwMjI2MTc1NCwicGF0aCI6Ii8yOTEzNTk4NC8yODk0MDkyNzktMWUyYmIwYWMtNDI1MS00ZTI1LWI3NWYtMWM1YzMzOWJhM2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyMjkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YTIwZGFlNTNjZjcyNjdhN2FjOGM2Yjk3MWFiYzRmYjVkZTIwNjJiODg2YWZkM2IzNTkwM2E4Nzg5YmRhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N4KLEfFAQuPtun3u3bbsqXD-Pe60Fjc8ehDCV70XPRY)

没有需求就不用填内容。不报错就行。

**Comment by DustinWin** [comment]
> 好的，启动merge文件，与不启动有差别吗？我比较小白...
那你最好按照我的教程来配置，这样用起来肯定没问题，参考：https://github.com/DustinWin/clash-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/%E5%88%86%E4%BA%AB%E7%AF%87/%E5%88%86%E4%BA%AB%E8%87%AA%E5%B7%B1%E4%BD%BF%E7%94%A8%20Clash%20Verge%20%E6%90%AD%E9%85%8D%20rule-set%20%E6%96%B9%E6%A1%88%E7%9A%84%E4%B8%80%E5%A5%97%E9%85%8D%E7%BD%AE.md

**Comment by DustinWin** [comment]
> 非常感谢，我按照你的教程操作了一遍，都没出现问题。但是从单位回到家后，依然会出现所有的节点无法连接的情况，我折腾半天重启就好了，这种情况正常吗？如果不是那如何解决呢？

有没有可能是机场不稳定或者订阅链接被污染。

**Comment by DustinWin** [comment]
> 没有，机场用了好几年了都没出过问题。刚才电脑休眠后唤醒就又连不上，弹出个窗，说什么机器积极拒绝，什么9090，没看完就消失了。我重启后就有没事儿了

那就不清楚了，下次截个图。

**Comment by DustinWin** [comment]
> ![image](https://private-user-images.githubusercontent.com/29135984/289744115-0ac52d3e-4189-41d1-9b7a-489c3318ffda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTk2MjEsIm5iZiI6MTcwMjM1OTMyMSwicGF0aCI6Ii8yOTEzNTk4NC8yODk3NDQxMTUtMGFjNTJkM2UtNDE4OS00MWQxLTliN2EtNDg5YzMzMThmZmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA1MzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNGRmMTIyZjkzYTUxZDM2ZWY1NDFiODlkZWYxZGZkYzkzOTkxM2EyNmNkYTJmM2MyMmFmMTU1MjBlYWNhNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luNMkiWEfrC9xzHrJRXUW2jrD0jiKrIITOEJErc557M) 与这条代码相关吗：external-controller-tls: 127.0.0.1:9090
> 
> clash verge的代理设置是这样的，跟这有关系吗？ ![image](https://private-user-images.githubusercontent.com/29135984/289748721-0f189095-1e5c-42da-b6ab-19e947774e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTk2MjEsIm5iZiI6MTcwMjM1OTMyMSwicGF0aCI6Ii8yOTEzNTk4NC8yODk3NDg3MjEtMGYxODkwOTUtMWU1Yy00MmRhLWI2YWItMTllOTQ3Nzc0ZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA1MzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYTRmODkyODllZGE3NGU2OWZlNDdiZWVjMmVkOTNlNWUxYjYzNzhjNGQ0MTYzOTk1ZjVlN2VkOWYxYTJhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gn0Tgfk7k_PsDRd9FJCgj8MMtfxRZS90997rV8bMvxo)

你不是用的 TUN 模式吗？改成 `external-controller` 试试？

**Comment by DustinWin** [comment]
> 不行啊，好像是定时就会停止访问。我还是想知道`taskkill /f /t /im "Clash Verge*"` `taskkill /f /t /im clash-meta*`是不是永久性地改变了什么设置？如果有，能改回来吗？如果没有我全部删除重装能解决吗？

这个命令只是结束进程而已，相当于在任务管理器里面结束 clash 相关进程。

**Comment by DustinWin** [comment]
> 感谢，如果我想把claude、bard、openai等等ai全部分流的话，有没有相应的规则呢？我搞了半天没有搞定

我的规则集 `ai` 里面没有 `claude`，其它的有。

**Comment by DustinWin** [comment]
> 手机的设置里也有点问题：`错误yaml: unmarshal errors:line 328: cannot unmarshal !!seq into string，`line 329: cannot unmarshal !seq into string`，也就是这两行： nameserver-policy: 'rule-set:cn,private': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query] 'rule-set:proxy': ['https://dns.google/dns-query#🪜 代理域名', 'https://cloudflare-dns.com/dns-query#🪜 代理域名']
> 
> 我把这两条删除后，还一个问题： initial rule provider ai error: Get "https://cdn.jsdelivr.net/gh/DustinWin/clash-ruleset@release/ai.yaml": dial tcp4 93.46.8.90:443: i/o timeout
> 
> 第三个问题：yaml : line 26: did not find expected key。也就是： `sniffer: enable: true sniff: {HTTP: {ports: [80, 8080-8880], override-destination: true}, TLS: {ports: [443, 8443]}, QUIC: {ports: [443, 8443]}} skip-domain: ['Mijia Cloud']`
> 
> 第四个问题：initial rule provider ads error: context deadline exceeded 每次存盘时都出不同的问题，老天这是要诚心为难我吗……
> 
> 第五个问题：initial rule provider ai error:netaddr.ParselPPrefix("+.ai.com"): no'/'

必须使用 clash.meta 内核，其它问题自行排查，在我的另外一个项目有教程，可参考。

**Comment by DustinWin** [comment]
> 非常感谢您的耐心💕，我好了

好的。

**Comment by DustinWin** [comment]
> 手机用了你的设置，都挺好的，只是ChatGPT的app在手机上无法使用，调试了好久也不行

不会啊，我这边是好的。
